[build]
  command = "yarn build"
  functions = "functions"
  publish = "functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200

[dev]
  command = "yarn start"
  port = 8888
  targetPort = 3001